# Generated by Django 2.1.7 on 2019-07-30 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read_statistic', '0004_auto_20190726_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipdeatil',
            name='ip_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ipdeatil',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='ipdeatil',
            name='id_blog',
            field=models.TextField(blank=True, null=True),
        ),
    ]
